language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -y --quiet --name gda_env --file requirements.txt python=${TRAVIS_PYTHON_VERSION}
  - source activate gda_env
  - git clone https://github.com/scipy/scipy-sphinx-theme
  - cd doc_src
  - ln -sf ../scipy-sphinx-theme/_theme ./
  - cd -
  - ls -lahrt doc_src/_theme/

script:
  - python setup.py build_ext --inplace
  - py.test
  - python setup.py build_doc_html
  - source deactivate
